version: '3'

services:
  backend:
    build: ./real-time-chat-backend-flask
    ports:
      - "5001:5000"
    depends_on:
      - mongo

  frontend:
    build: ./real-time-chat-frontend
    ports:
      - "3000:3000"

  mongo:
    image: "mongo:latest"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "27017:27017"
